server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 152388
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xinjingjie.springcloud.com.xinjingjie.springcloud.entities    # 所有Entity别名类所在包
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.137.1
    instance-id: payment8002
  client:
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
